/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8203139b-09e9-4d5a-9592-a961e9dc8f36",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jEosbo41P",
    "aws_user_pools_web_client_id": "2br0m1ail3g6l2mkb3168oeq8j",
    "oauth": {}
};


export default awsmobile;
